### ISSUE TITLE
ERROR:asyncio:An open stream object is being garbage collected; call "stream.close()" explicitly.

### ISSUE THREAD

**Issue by designfuchen** [Dineshkarthik/telegram_media_downloader#148]
**Describe the bug**

**To Reproduce**
Share the config: `Please don't share your api_hash & api_id`
```yaml
chat_id: telegram_chat_id
last_read_message_id: 0
media_types:
- audio
- photo
- video
- document
- voice
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```

**Python Version**
Python: [e.g. 3.7.7]

**OS:**
The OS and its version: [e.g. Ubuntu 20.04]

**Logs**
Logs showing the exception

**Additional context**
