### ISSUE TITLE
No download after running

### ISSUE THREAD

**Issue by 2284787774** [Dineshkarthik/telegram_media_downloader#160]
**Describe the bug**
No download after running

**To Reproduce**
Share the config: `Please don't share your api_hash & api_id`
```yaml
chat_id: -1001490386188
last_read_message_id: 0
ids_to_retry: []
media_types:
- audio
- photo
- video
- document
- voice
- video_note
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```

**Python Version**
Python: 3.7.11

**OS:**
DSM 6.2.3-25426 Update 3

**Logs**
root@U3865:~/telegram_media_downloader# python3 media_downloader.py
[21:38:27] Telegram Media Downloader v1.4.1,                                                                                                       

**Additional context**
