### ISSUE TITLE
Unable to connect due to network issues

### ISSUE THREAD

**Issue by rensonghua** [Dineshkarthik/telegram_media_downloader#162]
**Describe the bug**
Unable to connect due to network issues

**To Reproduce**
Share the config: `Please don't share your api_hash & api_id`
```yaml
chat_id: -1001713359795
last_read_message_id: 0
ids_to_retry: []
media_types:
- audio
- photo
- video
- document
- voice
- video_note
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all

```

**Python Version**
Python: [e.g. 3.6.5]

**OS:**
The OS and its version: [win10]

**Logs**
[16:07:17] Telegram Media Downloader v1.4.1,                         meta.py:21
           Copyright (C) 2019 Dineshkarthik                                    
           <https://github.com/Dineshkarthik>                                  
           Licensed under the terms of the MIT License               meta.py:23
                                                                               
[16:07:17] INFO     Device: CPython 3.6.5 - Telegram Media           meta.py:24
                    Downloader 1.4.1                                           
           INFO     System: Windows 10 (EN)                          meta.py:25
           INFO     Start creating a new auth key on DC2             auth.py:82
           INFO     Connecting...                              connection.py:56
[16:07:27] WARNING  Unable to connect due to network issues:   connection.py:59
                    timed out                                                  
[16:07:28] INFO     Connecting...                              connection.py:56
[16:07:38] WARNING  Unable to connect due to network issues:   connection.py:59
                    timed out                                                  
[16:07:39] INFO     Connecting...                              connection.py:56

**Additional context**
.
