### ISSUE TITLE
stop during operation

### ISSUE THREAD

**Issue by 2284787774** [Dineshkarthik/telegram_media_downloader#165]
**Describe the bug**
stop during operation

**To Reproduce**
Share the config: `Please don't share your api_hash & api_id`
```yaml
chat_id: -1001422899563
last_read_message_id: 0
ids_to_retry: []
media_types:
- audio
- photo
- video
- document
- voice
- video_note
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```

**Python Version**
Python: [e.g. 3.8.8]

**OS:**
DSM 7.0.1-42218 Update 2

**Logs**
INFO:media_downloader:Media downloaded - /volume1/photo/1001422899563/video/4.mp4
INFO:media_downloader:Media downloaded - /volume1/photo/1001422899563/video/0002.mp4
INFO:media_downloader:Media downloaded - /volume1/photo/1001422899563/video/sp (8).mp4
INFO:media_downloader:Media downloaded - /volume1/photo/1001422899563/video/1 (9).mp4
INFO:media_downloader:Media downloaded - /volume1/photo/1001422899563/video/1 (2).mp4
Traceback (most recent call last):
  File "/volume1/photo/1001422899563/media_downloader.py", line 361, in <module>
    main()
  File "/volume1/photo/1001422899563/media_downloader.py", line 345, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/volume1/photo/1001422899563/media_downloader.py", line 327, in begin_import
    update_config(config)
  File "/volume1/photo/1001422899563/media_downloader.py", line 34, in update_config
    config["ids_to_retry"] = list(set(config["ids_to_retry"] + FAILED_IDS))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

**Additional context**
