### ISSUE TITLE
channel ID invalid......

### ISSUE THREAD

**Issue by kklod** [Dineshkarthik/telegram_media_downloader#173]
**Describe the bug**
I use get_id_bot to get channel ID, and the program failed as below:
![image](https://user-images.githubusercontent.com/50442661/155446514-98e57c06-a639-47fd-9041-dfc9cc9a17c4.png)

**To Reproduce**
```yaml
chat_id: -1001574882038
last_read_message_id: 0
media_types:
- audio
- photo
- video
- document
- voice
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```

**Python Version**
Python: [e.g. 3.7.3]

**OS:**
The OS and its version:Debian GNU/Linux 10
