### ISSUE TITLE
ValueError: bad file descriptor

### ISSUE THREAD

**Issue by neganoob** [Dineshkarthik/telegram_media_downloader#211]
**Describe the bug**
I'm having _**ValueError: bad file descriptor**_ upon running after setup

**To Reproduce**
Share the config: `Please don't share your api_hash & api_id`
```yaml
chat_id: telegram_chat_id
last_read_message_id: 0
media_types:
- audio
- photo
- video
- document
- voice
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```

**Python Version**
Python: [e.g. 3.7.7]

**OS:**
The OS and its version: [e.g. Ubuntu 20.04]

**Logs**
_**Traceback (most recent call last):
  File "C:\Users\User\Desktop\telegram_media_downloader-1.5.1\media_downloader.py", line 379, in <module>
    print_meta(logger)
  File "C:\Users\User\Desktop\telegram_media_downloader-1.5.1\utils\meta.py", line 20, in print_meta
    console.log(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 2033, in log
    render_options = self.options
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1073, in options
    max_height=self.size.height,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1101, in size
    width, height = os.get_terminal_size()
ValueError: bad file descriptor**_

**Additional context**
