### ISSUE TITLE
Cannot find program pyrogram

### ISSUE THREAD

**Issue by sunny9t1** [Dineshkarthik/telegram_media_downloader#236]
**I tried to start the program then i got the error mentioned below.. then i looked for answers in the issues... after that i tried to put cd "C:\WINDOWS\system32\telegram_media_downloader\telegram_media_downloader" in the power shell then i got the following error**
Traceback (most recent call last):
  File "E:\Telegram\telegram_media_downloader-1.5.1\media_downloader.py", line 8, in <module>
    import pyrogram
ModuleNotFoundError: No module named 'pyrogram'
PS E:\Telegram\telegram_media_downloader-1.5.1>

**after putting cd "C:\WINDOWS\system32\telegram_media_downloader\telegram_media_downloader" in powershell i get this error**

cd : Cannot find path 'C:\WINDOWS\system32\telegram_media_downloader\telegram_media_downloader' because it does not
exist.
At line:1 char:1
+ cd "C:\WINDOWS\system32\telegram_media_downloader\telegram_media_down ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\WINDOWS\syst...edia_downloader:String) [Set-Location], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
**To Reproduce**
Share the config: `Please don't share your api_hash & api_id`
```yaml
chat_id: telegram_chat_id
last_read_message_id: 0
media_types:
- audio
- photo
- video
- document
- voice
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```

**Python Version**
Python: [e.g. 3.7.7]

**OS:**
The OS and its version: [e.g. Ubuntu 20.04]

**Logs**
Logs showing the exception

**Additional context**
