### ISSUE TITLE
Cannot download from a channel

### ISSUE THREAD

**Issue by albertopasqualetto** [Dineshkarthik/telegram_media_downloader#265]
**Describe the bug**
Create yaml, start program, login with number and otp, loop

**To Reproduce**
Share the config: `Please don't share your api_hash & api_id`
```yaml
chat_id: -1001155190734
last_read_message_id: 0
ids_to_retry: []
media_types:
# - audio
# - photo
- video
#- document
# - voice
# - video_note
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```

**Python Version**
Python: [e.g. 3.7.7] 3.10.2

**OS:**
The OS and its version: [e.g. Ubuntu 20.04] Windows 11

**Logs**
![image](https://user-images.githubusercontent.com/39854348/177606442-fbb68384-c490-42ba-b424-39051704fee3.png)

**Additional context**
It works in another channel
