### ISSUE TITLE
DeprecatioWarning

### ISSUE THREAD

**Issue by 99215194** [Dineshkarthik/telegram_media_downloader#268]
**Describe the bug**
![image](https://user-images.githubusercontent.com/52209166/178249196-fac7975f-e53d-42ec-a200-0ba519006082.png)
**To Reproduce**
Share the config: `Please don't share your api_hash & api_id`
```yaml
chat_id: telegram_chat_id
last_read_message_id: 0
media_types:
- audio
- photo
- video
- document
- voice
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```

**Python Version**
Python: [e.g. 3.10]

**OS:**
WINdows

**Logs**
Logs showing the exception

**Additional context**
