### ISSUE TITLE
Incomplete download

### ISSUE THREAD

**Issue by loeveo** [Dineshkarthik/telegram_media_downloader#29]
The app displays more than 4,000 media files. But after the program is downloaded, the statistics are only more than 2,000

**Comment by Dineshkarthik** [comment]
Did you include all the `media_types` as well as `file_formats` in your `config.yaml`

**Comment by loeveo** [comment]
Excuse me, the author, the file with the same name, do you adopt the method of overwriting and downloading?

**Comment by Dineshkarthik** [comment]
Did your `config.yaml` looked similar to below
```
api_hash: your_api_hash
api_id: your_api_id
chat_id: telegram_chat_id
last_read_message_id: 0 <-- 0 when you started the script
media_types: 
- audio
- photo
- video
- document
- voice
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```

Whether all media types - `audio, photo, video, document, voice` are present?
