### ISSUE TITLE
The program exits when it finishes the downloadt of the latest message.

### ISSUE THREAD

**Issue by 99215194** [Dineshkarthik/telegram_media_downloader#305]
**Describe the bug**
The program ends after downloading the latest message, and there are many old messages in front of it that have not been downloaded.

**To Reproduce**
Share the config: `Please don't share your api_hash & api_id`
```yaml
chat_id: -1001667402859
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
ids_to_retry: []
last_read_message_id: 152
media_types:
- audio
- photo
- video
- document
- voice
- video_note

```

**Python Version**
Python3.10.2

**OS:**
Windows11

**Logs**
INFO Media downloaded - E:\Hell\telegram_media_downloader\video\7月29日(1)-copy1.mp4 run.py:195
INFO Stopped 12 HandlerTasks dispatcher.py:167
INFO PingTask stopped session.py:268
INFO Disconnected connection.py:77
INFO NetworkTask stopped session.py:287
INFO Session stopped session.py:174
INFO PingTask stopped session.py:268
INFO Disconnected connection.py:77
INFO NetworkTask stopped session.py:287
INFO Session stopped session.py:174
INFO Updated last read message_id to config file

**Additional context**
I am so sorry to disturb you. But I meet some bugs when I use it.

It seems that this program would randomly download messages from the specific group, not download messages Chronologically. When the latest message in the group is downloaded, the program will not download other messages in the group. This bug leads to only a tiny part of the messages being downloaded. It shows this:

My English was poor, wishing you could understand what I mean.
Looking for your reply soon.
