### ISSUE TITLE
Many videos can't be downloaded

### ISSUE THREAD

**Issue by Jkkoi** [Dineshkarthik/telegram_media_downloader#312]
About 64% of the videos create the file correctly, but the file is empty (0kb) or exactly 1024kb
they cannot be played properly

```yaml
chat_id: telegram_chat_id
last_read_message_id: 1069
media_types:
- audio
- photo
- video
- document
- voice
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```

**Python Version**
Python: 3.10

**OS:**
Windows 11

**Logs**
No warn / error in logs
