### ISSUE TITLE
If the downloaded video has a duplicate file name, it will be overwritten

### ISSUE THREAD

**Issue by symbolChai** [Dineshkarthik/telegram_media_downloader#359]
**Describe the bug**
For example, if a downloaded video has a name of 1.mp4, the second downloaded video with a name of 1.mp4 will overwrite the previous one.
If this option can be configured in the configuration file, could you please tell me where to modify it? thanks!

```yaml
api_hash: 
api_id: 
chat_id: 
last_read_message_id: 0
ids_to_retry: []
media_types:
- video
file_formats:
  video:
  - all
```

@Dineshkarthik
