### ISSUE TITLE
it still download the same media file again.

### ISSUE THREAD

**Issue by jerryc127** [Dineshkarthik/telegram_media_downloader#371]
**Describe the bug**

it still download the same media file again.

**To Reproduce**
Share the config: `Please don't share your api_hash & api_id`
```yaml
api_hash: xxxx
api_id: xxxx
chat_id: xxxxxxxx
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
ids_to_retry: []
last_read_message_id: 15
media_types:
- audio
- photo
- video
- document
- voice
- video_note

```

**Python Version**
Python: [e.g. 3.7.7]

Python 3.8.10 (default, Jun 22 2022, 20:18:18) 

**OS:**
The OS and its version: [e.g. Ubuntu 20.04]

Ubuntu 20.04.5 LTS

**Logs**
Logs showing the exception

![image](https://user-images.githubusercontent.com/16351105/201690794-d324fb0e-7c80-4ab7-b4cb-059eee5d2542.png)
![image](https://user-images.githubusercontent.com/16351105/201690928-eb81e2ec-4e8c-407f-8b75-62ec49e41918.png)

**Additional context**
