### ISSUE TITLE
Run python3 media_ downloader. No response from py

### ISSUE THREAD

**Issue by RuoFeng2015** [Dineshkarthik/telegram_media_downloader#374]
**Describe the bug**

**To Reproduce**
Share the config: `Please don't share your api_hash & api_id`
```yaml
chat_id: telegram_chat_id
last_read_message_id: 0
media_types:
- audio
- photo
- video
- document
- voice
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```

**Python Version**
Python: [e.g. 3.11.0]

**OS:**
The OS and its version: [e.g. win11]

**Logs**
Logs showing the exception

**Additional context**
![image](https://user-images.githubusercontent.com/41161634/202891385-7499407e-8b16-4093-846c-8f1fc4e829bc.png)
