### ISSUE TITLE
GetChatHistory.get_chat_history() got an unexpected keyword argument 'reverse'

### ISSUE THREAD

**Issue by Exey** [Dineshkarthik/telegram_media_downloader#453]
**Describe the bug**
exception on py .\media_downloader.py

**To Reproduce**
```yaml
chat_id: -1001632935915
last_read_message_id: 0
media_types:
- audio
- photo
- video
- document
- voice
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```

**Python Version**
Python: 3.11.4
pyrogram-2.0.106

**OS:**
Windows 10
WindowsVersion
--------------
1809

**Logs**
Traceback (most recent call last):
  File "E:\tmd\x\media_downloader.py", line 376, in <module>
    main()
  File "E:\tmd\x\media_downloader.py", line 360, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Exey\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\tmd\x\media_downloader.py", line 313, in begin_import
    messages_iter = client.get_chat_history(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Exey\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\sync.py", line 53, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GetChatHistory.get_chat_history() got an unexpected keyword argument 'reverse'
