### ISSUE TITLE
Error with downloading specified file type - rar

### ISSUE THREAD

**Issue by jkowalski995** [Dineshkarthik/telegram_media_downloader#469]
**Describe the bug**
When setting file type to rar it won't download any rar even if the channel is full of rar archives.

**To Reproduce**
```yaml
chat_id: telegram_chat_id
last_read_message_id: 0
media_types:
- document
file_formats:
  document:
  - rar
```

**Python Version**
Python: [3.10.2]

**OS:**
The OS and its version: Kali Linux

**Additional context**
The problem exists only when choosing specific type - rar. When selecting all, rar files are downloaded.
