### ISSUE TITLE
0Mb downloaded files

### ISSUE THREAD

**Issue by jkowalski995** [Dineshkarthik/telegram_media_downloader#473]
**Describe the bug**
When downloading files a lot of them approx 70% is downloaded with size 0. However downloading them manually do not serve aany error.

**To Reproduce**
```yaml
chat_id: telegram_chat_id
last_read_message_id: 0
media_types:
- document
file_formats:
  document:
  - all
```

**Python Version**
Python: [3.10.2]

**OS:**
The OS and its version: Kali Linux
